name: release @next

on:
  push:
    branches:
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Authenticate github cli
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: release @next
      run: |
        git config --global user.email "tin@devtin.io"
        git config --global user.name "Martin Rafael Gonzalez"
        git checkout next
        npm ci
        yarn build && yarn test:all && yarn release:next
    - name: publish
      run: npm publish --access public --tag next
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
