name: pre-release

on:
  push:
    branches:
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Authenticate github cli
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Identify github user & fetch all tags
      run: |
        git config --global user.email "tin@devtin.io"
        git config --global user.name "Martin Rafael Gonzalez"
    - name: Retrieves commit history
      run: |
        git fetch origin next
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: pre-release
      run: |
        npm ci
        yarn lint && yarn build:wcoverage && yarn release && git push
