name: release @next

on:
  push:
    branches:
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Authenticate github cli
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: release @next
      run: |
        git config --global user.email "tin@devtin.io"
        git config --global user.name "Martin Rafael Gonzalez"
        git fetch origin next
        git checkout next
        npm ci
        yarn build:wcoverage && yarn test:all && yarn release
        git push
